apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: streaming-lab
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Ajit-Dengale/streaming-lab.git
    targetRevision: main
    path: kafka

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
